version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'kleaners-team'
    assignees:
      - 'kleaners-team'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'javascript'
    groups:
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
      nextjs:
        patterns:
          - 'next'
      testing:
        patterns:
          - '@testing-library/*'
          - 'jest'
          - 'vitest'
          - 'playwright'
      linting:
        patterns:
          - 'eslint*'
          - 'prettier'
